model_base_path: "D:/styledecouple_dinov3"
dino_model_id: "./pretrain_checkpoints/dinov3_vitl16_pretrain_lvd1689m-8aa4cbdd.pth"
siglip_model_id: "./pretrain_checkpoints/siglip2-large-patch16-256"
checkpoint_path: "./checkpoints/weart/checkpoint_epoch0100.safetensors"
dino_image_size: 224
siglip_image_size: 256
projector_hidden_dim: 2048
projector_num_layers: 3
dino_dim: 1024
siglip_dim: 1024
