model_base_path: "D:/styledecouple_dinov3"

model:
  dino_model_id: "./pretrain_checkpoints/dinov3_vitl16_pretrain_lvd1689m-8aa4cbdd.pth"
  dino_hub_model: "dinov3_vitl16"
  dino_hub_repo: "facebookresearch/dinov3:6876159a11b4df116f30f667f8c9888617df0751"
  siglip_model_id: "./pretrain_checkpoints/siglip2-large-patch16-256"
  dino_dim: 1024
  siglip_dim: 1024
  projector_hidden_dim: 2048
  projector_num_layers: 3
  projector_dropout: 0.1

preprocessing:
  dino_image_size: 224
  siglip_image_size: 256
  text_max_length: 64
  dino_mean: [0.485, 0.456, 0.406]
  dino_std: [0.229, 0.224, 0.225]
  siglip_mean: [0.5, 0.5, 0.5]
  siglip_std: [0.5, 0.5, 0.5]

checkpoint_path: "./checkpoints/weart/checkpoint_best.safetensors"
